financingRounds:
  - name: "seed"
    fullyDiluted: 20
    sharesIssued: 5
    issuePrice: 1.23
  - name: "series A"
    fullyDiluted: 200
    sharesIssued: 100
    issuePrice: 3.14

ownedShares:
  - roundIssued: 0
    amount: 1
  - roundIssued: 1
    amount: 2
  - roundIssued: 1
    amount: 2
